### ISSUE TITLE
Unable to read alarm notifier config

### ISSUE THREAD

**Issue by vgeannin** [nokia/OSSMediator#51]
Hi all, 

I have this error when I activate the "alarm_notifier" : 

> time="2024-10-15T10:52:32+02:00" level=error msg="Error parsing YAML file" error="yaml: line 4: did not find expected alphabetic or numeric character" tid=1148
> time="2024-10-15T10:52:32+02:00" level=error msg="Unable to read alarm notifier config" error="yaml: line 4: did not find expected alphabetic or numeric character" tid=1148
> 

Bellow my "alarm_notifier.yaml" file (I replace the webhook url by https://web_hook_url/ )
```
---
  webhook_url: "https://web_hook_url/"
  radio_alarm_filters:
    - specific_problem: *
  dac_alarm_filters:
    - alarm_id: *
  core_alarm_filters:
    - alarm_id: *
  alarm_sync_duration: 60
  group_events: false
  notify_clear_event: true
  message_format: ms_teams
```
collector version : 4.5-SNAPSHOT
